import { faEye, faEyeSlash } from '@fortawesome/free-regular-svg-icons';
import {
    faArrowDown,
    faArrowUp,
    faBasketShopping,
    faBriefcase,
    faBurger,
    faCar,
    faChartSimple,
    faChevronDown,
    faChevronRight,
    faChevronUp,
    faCloudArrowUp,
    faCopy,
    faGasPump,
    faGear,
    faGift,
    faDollarSign,
    faGifts,
    faGraduationCap,
    faLandmark,
    faMoneyBill,
    faMoneyBills,
    faPaw,
    faPen,
    faPiggyBank,
    faPlane,
    faPlus,
    faSackDollar,
    faStop,
    faTrash,
    faTrashCan,
} from '@fortawesome/free-solid-svg-icons';

const iconProvider = {
    faChevronDown,
    faEye,
    faEyeSlash,
    faGasPump,
    faBasketShopping,
    faBriefcase,
    faCar,
    faGear,
    faGift,
    faGraduationCap,
    faLandmark,
    faPaw,
    faPen,
    faSackDollar,
    faTrash,
    faPlus,
    faCopy,
    faCloudArrowUp,
    faStop,
    faChevronRight,
    faChevronUp,
    faTrashCan,
    faArrowDown,
    faArrowUp,
    faMoneyBill,
    faPlane,
    faBurger,
    faGifts,
    faMoneyBills,
    faChartSimple,
    faPiggyBank,
    faDollarSign,
};

export { iconProvider };
