import { faEye, faEyeSlash } from '@fortawesome/free-regular-svg-icons';
import {
    faArrowDown,
    faArrowUp,
    faBasketShopping,
    faBriefcase,
    faCar,
    faChevronDown,
    faCloudArrowUp,
    faCopy,
    faGasPump,
    faGear,
    faGift,
    faGraduationCap,
    faLandmark,
    faPaw,
    faPen,
    faChevronUp,
    faPlus,
    faSackDollar,
    faStop,
    faTrash,
} from '@fortawesome/free-solid-svg-icons';

const iconProvider = {
    faChevronDown,
    faChevronUp,
    faEye,
    faEyeSlash,
    faGasPump,
    faBasketShopping,
    faBriefcase,
    faCar,
    faGear,
    faGift,
    faGraduationCap,
    faLandmark,
    faPaw,
    faPen,
    faSackDollar,
    faTrash,
    faPlus,
    faCopy,
    faCloudArrowUp,
    faStop,
    faArrowDown,
    faArrowUp,
};

export { iconProvider };
