enum FaIcons {
    CHEVRON_DOWN = 'chevron-down',
    CHEVRON_UP = 'chevron-up',
    EYE = 'eye',
    EYE_SLASH = 'eye-slash',
    PLUS = 'plus',
    FA_REGULAR = 'far',
    FA_PEN = 'pen',
    BASKET_SHOPPING = 'basket-shopping',
    PAW = 'paw',
    CAR = 'car',
    LANDMARK = 'landmark',
    GIFT = 'gift',
    SACK_DOLLAR = 'sack-dollar',
    GRADUATION_CAP = 'graduation-cap',
    BRIEFCASE = 'briefcase',
    GAS_PUMP = 'gas-pump',
    GEAR = 'gear',
    TRASH = 'trash',
    COPY = 'copy',
    CLOUD_ARROW_UP = 'cloud-arrow-up',
    STOP = 'stop',
    ARROW_DOWN = 'arrow-down',
    ARROW_UP = 'arrow-up',
    TRASH_CAN = 'trash-can',
}

export { FaIcons };
